-- ============================================================
-- DDL: Vistas y Tablas de Soporte para Fase 2 (Costos)
-- ============================================================

-- ---------------------------------------------------------
-- Tabla: AUCO_COSTOSCLUS (costos por clúster)
-- ---------------------------------------------------------
CREATE TABLE AUCO_COSTOSCLUS (
    COST_ID         NUMBER NOT NULL,
    EMPR_EMPR       NUMBER NOT NULL,
    DIVI_DIVI       NUMBER NOT NULL,
    PARA_COSTO20021 NUMBER NOT NULL,
    COST_ANNO       NUMBER NOT NULL,
    COST_MES        NUMBER NOT NULL,
    COST_VARIACION  FLOAT(126) DEFAULT 0,
    COST_VALOR      FLOAT(126) DEFAULT 0 NOT NULL,
    COST_MEDIOVALOR FLOAT(126) DEFAULT 0,
    COST_ACOBRAR    FLOAT(126) DEFAULT 0,
    COST_FECHACREACION DATE DEFAULT SYSDATE,
    USUA_USUA       NUMBER NOT NULL,
    CONSTRAINT PK_AUCO_COSTOSCLUS PRIMARY KEY (COST_ID)
);

-- ---------------------------------------------------------
-- Vista: VACUO_COSTOSCLUS (costos por clúster consulta)
-- ---------------------------------------------------------
CREATE OR REPLACE VIEW VACUO_COSTOSCLUS AS
SELECT 
    APSA_ID,
    COST_ANNO,
    COST_MES,
    PARA_COSTO20021,
    'COSTO CLUSTER ' || PARA_COSTO20021 AS PARA_NOMBRE,
    COST_VALOR
FROM AUCO_COSTOSCLUS
WHERE COST_ANNO >= 2024;

-- ---------------------------------------------------------
-- Tabla: AUCO_INDICADORES (indicadores para VAUCO_ACTICLUS)
-- ---------------------------------------------------------
CREATE TABLE AUCO_INDICADORES (
    INED_ID         NUMBER NOT NULL,
    APSA_ID         NUMBER NOT NULL,
    INED_ANNO       NUMBER NOT NULL,
    INED_MES        NUMBER NOT NULL,
    INED_CP         FLOAT(126) DEFAULT 0,
    INED_M2CCJ      FLOAT(126) DEFAULT 0,
    INED_M2LAVJ     FLOAT(126) DEFAULT 0,
    INED_TIJ        FLOAT(126) DEFAULT 0,
    INED_KLPJ       FLOAT(126) DEFAULT 0,
    INED_TMJ        FLOAT(126) DEFAULT 0,
    INED_FECHACREACION DATE DEFAULT SYSDATE,
    USUA_USUA       NUMBER NOT NULL,
    CONSTRAINT PK_AUCO_INDICADORES PRIMARY KEY (INED_ID)
);

-- ---------------------------------------------------------
-- Vista: VAUCO_ACTICLUS (comportamiento histórico clúster)
-- ---------------------------------------------------------
CREATE OR REPLACE VIEW VAUCO_ACTICLUS AS
SELECT 
    APSA_ID,
    INED_ANNO,
    INED_MES,
    INED_CP,
    INED_M2CCJ,
    INED_M2LAVJ,
    INED_TIJ,
    INED_KLPJ,
    INED_TMJ
FROM AUCO_INDICADORES;

-- ---------------------------------------------------------
-- Secuencias
-- ---------------------------------------------------------
CREATE SEQUENCE SAUCO_COSTOSCLUS
    MINVALUE 1 MAXVALUE 9999999999999999999999999999
    INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE SAUCO_INDICADORES
    MINVALUE 1 MAXVALUE 9999999999999999999999999999
    INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;

-- ---------------------------------------------------------
-- Datos de prueba: AUCO_COSTOSCLUS
-- ---------------------------------------------------------
INSERT INTO AUCO_COSTOSCLUS (COST_ID, EMPR_EMPR, DIVI_DIVI, PARA_COSTO20021, COST_ANNO, COST_MES, COST_VALOR, USUA_USUA)
VALUES (SAUCO_COSTOSCLUS.NEXTVAL, 1, 11001, 1, 2025, 4, 150000, 1);

INSERT INTO AUCO_COSTOSCLUS (COST_ID, EMPR_EMPR, DIVI_DIVI, PARA_COSTO20021, COST_ANNO, COST_MES, COST_VALOR, USUA_USUA)
VALUES (SAUCO_COSTOSCLUS.NEXTVAL, 1, 11001, 2, 2025, 4, 250000, 1);

INSERT INTO AUCO_COSTOSCLUS (COST_ID, EMPR_EMPR, DIVI_DIVI, PARA_COSTO20021, COST_ANNO, COST_MES, COST_VALOR, USUA_USUA)
VALUES (SAUCO_COSTOSCLUS.NEXTVAL, 2, 11001, 1, 2025, 4, 180000, 1);

-- ---------------------------------------------------------
-- Datos de prueba: AUCO_INDICADORES (últimos 6 meses para APS 1)
-- ---------------------------------------------------------
INSERT INTO AUCO_INDICADORES (INED_ID, APSA_ID, INED_ANNO, INED_MES, INED_CP, INED_M2CCJ, INED_M2LAVJ, INED_TIJ, INED_KLPJ, INED_TMJ, USUA_USUA)
VALUES (SAUCO_INDICADORES.NEXTVAL, 1, 2024, 11, 120.5, 45000, 32000, 85.2, 1250.5, 3400, 1);

INSERT INTO AUCO_INDICADORES (INED_ID, APSA_ID, INED_ANNO, INED_MES, INED_CP, INED_M2CCJ, INED_M2LAVJ, INED_TIJ, INED_KLPJ, INED_TMJ, USUA_USUA)
VALUES (SAUCO_INDICADORES.NEXTVAL, 1, 2024, 12, 121.3, 45200, 32100, 85.5, 1260.0, 3410, 1);

INSERT INTO AUCO_INDICADORES (INED_ID, APSA_ID, INED_ANNO, INED_MES, INED_CP, INED_M2CCJ, INED_M2LAVJ, INED_TIJ, INED_KLPJ, INED_TMJ, USUA_USUA)
VALUES (SAUCO_INDICADORES.NEXTVAL, 1, 2025, 1, 122.1, 45500, 32250, 85.8, 1265.2, 3420, 1);

INSERT INTO AUCO_INDICADORES (INED_ID, APSA_ID, INED_ANNO, INED_MES, INED_CP, INED_M2CCJ, INED_M2LAVJ, INED_TIJ, INED_KLPJ, INED_TMJ, USUA_USUA)
VALUES (SAUCO_INDICADORES.NEXTVAL, 1, 2025, 2, 123.0, 45800, 32400, 86.1, 1270.5, 3430, 1);

INSERT INTO AUCO_INDICADORES (INED_ID, APSA_ID, INED_ANNO, INED_MES, INED_CP, INED_M2CCJ, INED_M2LAVJ, INED_TIJ, INED_KLPJ, INED_TMJ, USUA_USUA)
VALUES (SAUCO_INDICADORES.NEXTVAL, 1, 2025, 3, 123.8, 46000, 32500, 86.4, 1275.8, 3440, 1);

INSERT INTO AUCO_INDICADORES (INED_ID, APSA_ID, INED_ANNO, INED_MES, INED_CP, INED_M2CCJ, INED_M2LAVJ, INED_TIJ, INED_KLPJ, INED_TMJ, USUA_USUA)
VALUES (SAUCO_INDICADORES.NEXTVAL, 1, 2025, 4, 124.5, 46200, 32600, 86.7, 1280.0, 3450, 1);

-- Datos para APS 2
INSERT INTO AUCO_INDICADORES (INED_ID, APSA_ID, INED_ANNO, INED_MES, INED_CP, INED_M2CCJ, INED_M2LAVJ, INED_TIJ, INED_KLPJ, INED_TMJ, USUA_USUA)
VALUES (SAUCO_INDICADORES.NEXTVAL, 2, 2025, 4, 130.2, 48000, 34000, 90.1, 1350.5, 3600, 1);

COMMIT;
