-- ============================================================
-- ASIGNAR PERMISOS A USUARIO ADMIN PARA SISTEMAS 2 Y 3
-- Usando secuencia SAUGE_USUAMENU
-- ============================================================

-- Sistema 2: Todos los menus
INSERT INTO AUGE_USUAMENU (USME_ID, SISU_ID, MENU_ID, USME_ESTADO)
SELECT SAUGE_USUAMENU.NEXTVAL, 1, MENU_ID, 1
FROM AUGE_MENU
WHERE MENU_SISTEMA = 2 AND MENU_ESTADO = 1;

-- Sistema 3: Todos los menus
INSERT INTO AUGE_USUAMENU (USME_ID, SISU_ID, MENU_ID, USME_ESTADO)
SELECT SAUGE_USUAMENU.NEXTVAL, 1, MENU_ID, 1
FROM AUGE_MENU
WHERE MENU_SISTEMA = 3 AND MENU_ESTADO = 1;

COMMIT;

-- Verificacion
SELECT 'Permisos asignados:' FROM dual;
SELECT m.MENU_SISTEMA, COUNT(*) as menus 
FROM AUGE_USUAMENU um 
JOIN AUGE_MENU m ON um.MENU_ID = m.MENU_ID 
WHERE um.SISU_ID = 1 
GROUP BY m.MENU_SISTEMA 
ORDER BY m.MENU_SISTEMA;

-- Verificar menus por sistema
SELECT 'Menus sistema 2:' FROM dual;
SELECT MENU_ID, MENU_NOMBRE, MENU_PATH FROM AUGE_MENU WHERE MENU_SISTEMA = 2 AND MENU_ESTADO = 1 ORDER BY MENU_ID;

SELECT 'Menus sistema 3 (primeros 10):' FROM dual;
SELECT MENU_ID, MENU_NOMBRE, MENU_PATH FROM AUGE_MENU WHERE MENU_SISTEMA = 3 AND MENU_ESTADO = 1 ORDER BY MENU_ID FETCH FIRST 10 ROWS ONLY;
