CREATE TABLE "AUCO_INDICESCRA" (
  "INDI_ID" NUMBER NOT NULL PRIMARY KEY,
  "PARA_INDICE20011" NUMBER NOT NULL,
  "INDI_ANNO" NUMBER NOT NULL,
  "INDI_MES" NUMBER NOT NULL,
  "INDI_ESTADO" NUMBER DEFAULT 1 NOT NULL,
  "INDI_VALOR" NUMBER,
  "INDI_MITADVALOR" NUMBER,
  "INDI_FECHACREACION" DATE DEFAULT SYSDATE,
  "USUA_USUA" NUMBER
);

CREATE SEQUENCE "SAUCO_INDICESCRA" START WITH 1 INCREMENT BY 1;

CREATE INDEX "IDX_INDICESCRA_PERIODO" ON "AUCO_INDICESCRA"("INDI_ANNO", "INDI_MES", "INDI_ESTADO");

INSERT INTO "AUCO_INDICESCRA" (
  "INDI_ID", "PARA_INDICE20011", "INDI_ANNO", "INDI_MES", "INDI_ESTADO", "INDI_VALOR", "INDI_MITADVALOR", "USUA_USUA"
) VALUES (SAUCO_INDICESCRA.NEXTVAL, 1, 2026, 1, 1, 100, 50, 1);

INSERT INTO "AUCO_INDICESCRA" (
  "INDI_ID", "PARA_INDICE20011", "INDI_ANNO", "INDI_MES", "INDI_ESTADO", "INDI_VALOR", "INDI_MITADVALOR", "USUA_USUA"
) VALUES (SAUCO_INDICESCRA.NEXTVAL, 2, 2026, 1, 1, 200, 100, 1);

INSERT INTO "AUCO_INDICESCRA" (
  "INDI_ID", "PARA_INDICE20011", "INDI_ANNO", "INDI_MES", "INDI_ESTADO", "INDI_VALOR", "INDI_MITADVALOR", "USUA_USUA"
) VALUES (SAUCO_INDICESCRA.NEXTVAL, 3, 2026, 1, 1, 300, 150, 1);

INSERT INTO "AUCO_INDICESCRA" (
  "INDI_ID", "PARA_INDICE20011", "INDI_ANNO", "INDI_MES", "INDI_ESTADO", "INDI_VALOR", "INDI_MITADVALOR", "USUA_USUA"
) VALUES (SAUCO_INDICESCRA.NEXTVAL, 4, 2026, 1, 1, 400, 200, 1);

COMMIT;
