-- Secuencias
CREATE SEQUENCE SPROY_PROYECCION START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SPROY_SUBSCONTEMP START WITH 1 INCREMENT BY 1;

-- 1. PROY_PROYECCION
CREATE TABLE PROY_PROYECCION (
  PROYID NUMBER PRIMARY KEY,
  APSA_ID NUMBER NOT NULL,
  PROYNOMBRE VARCHAR2(200) NOT NULL,
  PROYTIPO100 NUMBER DEFAULT 1,
  PROYANNODES NUMBER NOT NULL,
  PROYMESDES NUMBER NOT NULL,
  PROYANNOHAS NUMBER NOT NULL,
  PROYMESHAS NUMBER NOT NULL,
  PROYESTADO NUMBER DEFAULT 1,
  USUA_USUA NUMBER,
  PROYFECHA DATE DEFAULT SYSDATE
);

-- 2. PROY_DETLINEATIEMPO
CREATE TABLE PROY_DETLINEATIEMPO (
  PROYID NUMBER NOT NULL,
  APS NUMBER NOT NULL,
  PROYANNO NUMBER NOT NULL,
  PROYMES NUMBER NOT NULL,
  DELTIPC NUMBER,
  DELTIPCC NUMBER,
  DELTSMLV NUMBER,
  DELTIOEXP NUMBER,
  DELTFACPRODUC NUMBER,
  DELTFECHA DATE,
  USUARIO NUMBER,
  DELTINDIPCC NUMBER,
  DELTIPCCS NUMBER,
  CONSTRAINT PK_PROY_DETLINEATIEMPO PRIMARY KEY (PROYID, APS, PROYANNO, PROYMES)
);

-- 3. PROY_CRECIMIENTO_VBLES
CREATE TABLE PROY_CRECIMIENTO_VBLES (
  PROCV_ID NUMBER PRIMARY KEY,
  APSA_ID NUMBER NOT NULL,
  PROYID NUMBER NOT NULL,
  ID_ARCHIVO VARCHAR2(500),
  LISTA_HOJAS VARCHAR2(500),
  ESTADO NUMBER DEFAULT 1
);

-- 4. PROY_USUARIOS -- sin ID sustituto, clave natural (PROY_ID, COD_APS, ANNO, SEMESTRE, CODTIPOPRED, CODUSO)
CREATE TABLE PROY_USUARIOS (
  PROY_ID NUMBER NOT NULL,
  COD_APS NUMBER NOT NULL,
  ANNO NUMBER NOT NULL,
  SEMESTRE NUMBER NOT NULL,
  CODUSO NUMBER,
  NOMCLASEUSO VARCHAR2(100),
  CODFACTOR NUMBER,
  VALORFACTOR NUMBER,
  CODTIPOPRED NUMBER,
  NOMTIPOPRED VARCHAR2(100),
  CANTIDAD NUMBER,
  TONELADAS NUMBER,
  FECHACREA DATE,
  USUARIO NUMBER
);

-- 5. PROY_PROPIA -- sin ID sustituto. Variables de cálculo propio del APS
-- (~40 columnas V_*), no un resumen genérico usuarios/toneladas/ingresos/costos.
CREATE TABLE PROY_PROPIA (
  PROY_ID NUMBER NOT NULL,
  COD_APS NUMBER NOT NULL,
  NOM_APS VARCHAR2(200),
  COD_EMPRESA NUMBER,
  NOM_EMPRESA VARCHAR2(200),
  ANNO NUMBER NOT NULL,
  MES NUMBER NOT NULL,
  V_DISPTERC VARCHAR2(10), IAT VARCHAR2(10), V_N NUMBER, V_NA NUMBER, V_ND NUMBER,
  V_TAFNA NUMBER, V_QRT NUMBER, V_QLU NUMBER, V_QNA NUMBER, V_QBL NUMBER,
  V_QR NUMBER, V_QRS NUMBER, V_CBLJ NUMBER, V_LBL NUMBER, V_VALOR_MTS3 NUMBER,
  V_M2CC NUMBER, V_M2LAV NUMBER, V_TI NUMBER, V_TM NUMBER, V_KLP NUMBER,
  V_VL NUMBER, V_ESCENARIO NUMBER, V_CTLMX NUMBER, V_T NUMBER, V_CPE NUMBER,
  V_VA_CRT NUMBER, V_VA_CRT_ABC NUMBER, V_VA_CDF NUMBER, V_VA_CDF_ABC NUMBER, V_NAA NUMBER,
  V_QA NUMBER, V_TAFA NUMBER, V_CP NUMBER, V_CRT_PROPIO NUMBER, V_CDF_FACTURADO NUMBER,
  V_QRTZ NUMBER, V_CDF_TERCERO NUMBER, V_CTL_TERCERO NUMBER, V_IR_TERCERO NUMBER, V_QRS_MUNRECP NUMBER,
  FECHACREA DATE,
  USUARIO NUMBER
);

-- 6. PROY_COMPETIDOR -- sin ID sustituto. Variables del competidor/tercero (~37 columnas C_*).
CREATE TABLE PROY_COMPETIDOR (
  PROY_ID NUMBER NOT NULL,
  COD_APS NUMBER NOT NULL,
  NOM_APS VARCHAR2(200),
  COD_EMPRESA NUMBER,
  NOM_EMPRESA VARCHAR2(200),
  ANNO NUMBER NOT NULL,
  MES NUMBER NOT NULL,
  C_N NUMBER, C_NA NUMBER, C_ND NUMBER, C_TAFNA NUMBER, C_VALOR_MTS3 NUMBER,
  C_QRT NUMBER, C_QLU NUMBER, C_QNA NUMBER, C_QBL NUMBER, C_QRECHAZO NUMBER,
  C_QRS NUMBER, C_CBLJ NUMBER, C_LBL NUMBER, C_M2CC NUMBER, C_M2LAV NUMBER,
  C_TI NUMBER, C_TM NUMBER, C_KLP NUMBER, C_VL NUMBER, C_ESCENARIO NUMBER,
  C_T NUMBER, C_CPE NUMBER, C_CTLMX NUMBER, C_VA_CRT NUMBER, C_VA_CRT_ABC NUMBER,
  C_VA_CDF NUMBER, C_VA_CDF_ABC NUMBER, C_NAA NUMBER, C_QA NUMBER, C_TAFA NUMBER,
  C_CRT_COMPETIDOR NUMBER, C_CDF_COMPETIDOR NUMBER, C_QRTZ NUMBER, C_CTL_SIN_INCENTIVO NUMBER, C_INCENTIVO NUMBER,
  C_CDFSINCENTIVO NUMBER, C_CPODA NUMBER,
  FECHACREA DATE,
  USUARIO NUMBER
);

-- 7. PROY_DESCUENTOS -- sin ID sustituto, clave natural (PROY_ID, ANNO, MES)
CREATE TABLE PROY_DESCUENTOS (
  PROY_ID NUMBER NOT NULL,
  COD_APS NUMBER,
  NOM_APS VARCHAR2(200),
  ANNO NUMBER NOT NULL,
  MES NUMBER NOT NULL,
  D_CCS NUMBER,
  D_CBL NUMBER,
  D_CLUS NUMBER,
  D_CRT NUMBER,
  D_CDF NUMBER,
  D_CTL NUMBER,
  D_VBA NUMBER,
  FECHACREA DATE,
  USUARIO NUMBER
);

-- 8. PROY_APSSUBSCONT -- solo lectura para la app (la llena el proceso de
-- ejecución de la proyección, no un INSERT nuestro), sin ID sustituto conocido.
CREATE TABLE PROY_APSSUBSCONT (
  PROY_ID NUMBER NOT NULL,
  APSA_ID NUMBER NOT NULL,
  CLAS_CLASE NUMBER NOT NULL,
  SUCO_VALOR NUMBER,
  SUCO_ANNO NUMBER,
  SUCO_MES NUMBER
);

-- 9. PROY_SUBSCONTEMP -- staging de ediciones pendientes de aplicar.
CREATE TABLE PROY_SUBSCONTEMP (
  SUCO_ID NUMBER PRIMARY KEY,
  PROY_ID NUMBER NOT NULL,
  APSA_ID NUMBER NOT NULL,
  CLAS_CLASE NUMBER NOT NULL,
  SUCO_ANNO NUMBER,
  SUCO_MES NUMBER,
  SUCO_VALOR NUMBER,
  SUCO_ESTADO NUMBER,
  SUCO_FECHA DATE DEFAULT SYSDATE,
  USUA_USUA NUMBER
);

-- 10. PROY_EJECUCION
CREATE TABLE PROY_EJECUCION (
  PROYEJ_ID NUMBER PRIMARY KEY,
  PROYID NUMBER NOT NULL,
  APSA_ID NUMBER NOT NULL,
  EJEC_FECHA DATE DEFAULT SYSDATE,
  EJEC_USUARIO NUMBER,
  RESULTADO VARCHAR2(50),
  MENSAJE VARCHAR2(4000)
);

-- Stub package
CREATE OR REPLACE PACKAGE PK_PROYLIQUIDA AS
  FUNCTION fproy_proyectar(p_proy_id NUMBER, p_apsa_id NUMBER, p_usuario NUMBER) RETURN VARCHAR2;
END PK_PROYLIQUIDA;
/

CREATE OR REPLACE PACKAGE BODY PK_PROYLIQUIDA AS
  FUNCTION fproy_proyectar(p_proy_id NUMBER, p_apsa_id NUMBER, p_usuario NUMBER) RETURN VARCHAR2 IS
  BEGIN
    RETURN 'STUB_OK';
  END;
END PK_PROYLIQUIDA;
/
