-- Secuencias
CREATE SEQUENCE SPROY_PROYECCION START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SPROY_SUBSCONTEMP START WITH 1 INCREMENT BY 1;

-- 1. PROY_PROYECCION
CREATE TABLE PROY_PROYECCION (
  PROYID NUMBER PRIMARY KEY,
  APSA_ID NUMBER NOT NULL,
  PROYNOMBRE VARCHAR2(200) NOT NULL,
  PROYTIPO100 NUMBER DEFAULT 1,
  PROYANNODES NUMBER NOT NULL,
  PROYMESDES NUMBER NOT NULL,
  PROYANNOHAS NUMBER NOT NULL,
  PROYMESHAS NUMBER NOT NULL,
  PROYESTADO NUMBER DEFAULT 1,
  USUA_USUA NUMBER,
  PROYFECHA DATE DEFAULT SYSDATE
);

-- 2. PROY_DETLINEATIEMPO
CREATE TABLE PROY_DETLINEATIEMPO (
  PROYID NUMBER NOT NULL,
  APS NUMBER NOT NULL,
  PROYANNO NUMBER NOT NULL,
  PROYMES NUMBER NOT NULL,
  DELTIPC NUMBER,
  DELTIPCC NUMBER,
  DELTSMLV NUMBER,
  DELTIOEXP NUMBER,
  DELTFACPRODUC NUMBER,
  DELTFECHA DATE,
  USUARIO NUMBER,
  DELTINDIPCC NUMBER,
  DELTIPCCS NUMBER,
  CONSTRAINT PK_PROY_DETLINEATIEMPO PRIMARY KEY (PROYID, APS, PROYANNO, PROYMES)
);

-- 3. PROY_CRECIMIENTO_VBLES
CREATE TABLE PROY_CRECIMIENTO_VBLES (
  PROCV_ID NUMBER PRIMARY KEY,
  APSA_ID NUMBER NOT NULL,
  PROYID NUMBER NOT NULL,
  ID_ARCHIVO VARCHAR2(500),
  LISTA_HOJAS VARCHAR2(500),
  ESTADO NUMBER DEFAULT 1
);

-- 4. PROY_USUARIOS
CREATE TABLE PROY_USUARIOS (
  PRUS_ID NUMBER PRIMARY KEY,
  PROYID NUMBER NOT NULL,
  APSA_ID NUMBER NOT NULL,
  ANNO NUMBER NOT NULL,
  SEMESTRE NUMBER NOT NULL,
  CODUSO NUMBER,
  CODTIPOPRED NUMBER,
  CANTIDAD NUMBER,
  TONELADAS NUMBER
);

-- 5. PROY_PROPIA
CREATE TABLE PROY_PROPIA (
  PRPR_ID NUMBER PRIMARY KEY,
  PROYID NUMBER NOT NULL,
  APSA_ID NUMBER NOT NULL,
  ANNO NUMBER NOT NULL,
  MES NUMBER NOT NULL,
  V_USUARIOS NUMBER,
  V_TONELADAS NUMBER,
  V_INGRESOS NUMBER,
  V_COSTOS NUMBER
);

-- 6. PROY_COMPETIDOR
CREATE TABLE PROY_COMPETIDOR (
  PRCO_ID NUMBER PRIMARY KEY,
  PROYID NUMBER NOT NULL,
  APSA_ID NUMBER NOT NULL,
  ANNO NUMBER NOT NULL,
  MES NUMBER NOT NULL,
  C_USUARIOS NUMBER,
  C_TONELADAS NUMBER,
  C_INGRESOS NUMBER,
  C_COSTOS NUMBER
);

-- 7. PROY_DESCUENTOS
CREATE TABLE PROY_DESCUENTOS (
  PRDE_ID NUMBER PRIMARY KEY,
  PROYID NUMBER NOT NULL,
  APSA_ID NUMBER NOT NULL,
  ANNO NUMBER NOT NULL,
  MES NUMBER NOT NULL,
  PORCENTAJE NUMBER,
  VALOR NUMBER
);

-- 8. PROY_APSSUBSCONT
CREATE TABLE PROY_APSSUBSCONT (
  PRAS_ID NUMBER PRIMARY KEY,
  PROYID NUMBER NOT NULL,
  APSA_ID NUMBER NOT NULL,
  CLAS_CLASE NUMBER NOT NULL,
  SUCO_VALOR NUMBER,
  SUCO_ANNO NUMBER,
  SUCO_MES NUMBER
);

-- 9. PROY_SUBSCONTEMP
CREATE TABLE PROY_SUBSCONTEMP (
  SUCO_ID NUMBER PRIMARY KEY,
  PROYID NUMBER NOT NULL,
  APSA_ID NUMBER NOT NULL,
  CLAS_CLASE NUMBER NOT NULL,
  SUCO_VALOR NUMBER,
  SUCO_ANNO NUMBER,
  SUCO_MES NUMBER,
  USUA_USUA NUMBER,
  FECHA DATE DEFAULT SYSDATE
);

-- 10. PROY_EJECUCION
CREATE TABLE PROY_EJECUCION (
  PROYEJ_ID NUMBER PRIMARY KEY,
  PROYID NUMBER NOT NULL,
  APSA_ID NUMBER NOT NULL,
  EJEC_FECHA DATE DEFAULT SYSDATE,
  EJEC_USUARIO NUMBER,
  RESULTADO VARCHAR2(50),
  MENSAJE VARCHAR2(4000)
);

-- Stub package
CREATE OR REPLACE PACKAGE PK_PROYLIQUIDA AS
  FUNCTION fproy_proyectar(p_proy_id NUMBER, p_apsa_id NUMBER, p_usuario NUMBER) RETURN VARCHAR2;
END PK_PROYLIQUIDA;
/

CREATE OR REPLACE PACKAGE BODY PK_PROYLIQUIDA AS
  FUNCTION fproy_proyectar(p_proy_id NUMBER, p_apsa_id NUMBER, p_usuario NUMBER) RETURN VARCHAR2 IS
  BEGIN
    RETURN 'STUB_OK';
  END;
END PK_PROYLIQUIDA;
/
