-- Secuencia RELIQ
CREATE SEQUENCE SRELQRELIQUIDA START WITH 1 INCREMENT BY 1;

-- 1. Cabecera reliquidación
CREATE TABLE RELQRELIQUIDA (
  RELQID NUMBER PRIMARY KEY,
  APSA_ID NUMBER NOT NULL,
  RELQNOMBRE VARCHAR2(200) NOT NULL,
  RELQDESCRIPCION VARCHAR2(500),
  RELQDESDE VARCHAR2(6) NOT NULL,
  RELQHASTA VARCHAR2(6) NOT NULL,
  RELQESTADO VARCHAR2(20) DEFAULT 'CREADA' NOT NULL,
  USUA_USUA NUMBER,
  RELQFECHA DATE DEFAULT SYSDATE,
  CONSTRAINT CK_RELQ_ESTADO CHECK (RELQESTADO IN ('CREADA', 'APLICADA'))
);

-- 2. Filtro comparativo de costos
CREATE TABLE FILTRO_COMPARACOSTO (
  FICO_ID NUMBER PRIMARY KEY,
  RELQID NUMBER NOT NULL,
  APSA_ID NUMBER NOT NULL,
  ANNO NUMBER,
  MES NUMBER,
  USUA_USUA NUMBER,
  FECHA DATE DEFAULT SYSDATE,
  CONSTRAINT FK_FICO_RELQ FOREIGN KEY (RELQID) REFERENCES RELQRELIQUIDA (RELQID)
);

-- 3. Cargue usuarios
CREATE TABLE RELI_INFUSUAPSEMPRDIVI (
  IUAE_ID NUMBER PRIMARY KEY,
  RELI_ID NUMBER NOT NULL,
  CODUSO NUMBER,
  CODTIPOPRED NUMBER,
  CANTIDAD NUMBER,
  TONELADAS NUMBER,
  USUA_USUA NUMBER,
  FECHA DATE DEFAULT SYSDATE,
  CONSTRAINT FK_IUAE_RELQ FOREIGN KEY (RELI_ID) REFERENCES RELQRELIQUIDA (RELQID)
);

-- 4. Cargue empresa
CREATE TABLE RELI_INFOEMPRDIVI (
  INED_ID NUMBER PRIMARY KEY,
  RELI_ID NUMBER NOT NULL,
  CBLJ NUMBER,
  COSTO NUMBER,
  TARIFA NUMBER,
  USUA_USUA NUMBER,
  FECHA DATE DEFAULT SYSDATE,
  CONSTRAINT FK_INED_RELQ FOREIGN KEY (RELI_ID) REFERENCES RELQRELIQUIDA (RELQID)
);

-- 5. Cargue APS
CREATE TABLE RELI_INFOAPSEMPRDIVI (
  IAED_ID NUMBER PRIMARY KEY,
  RELI_ID NUMBER NOT NULL,
  QRTZ NUMBER,
  COSTO NUMBER,
  TARIFA NUMBER,
  USUA_USUA NUMBER,
  FECHA DATE DEFAULT SYSDATE,
  CONSTRAINT FK_IAED_RELQ FOREIGN KEY (RELI_ID) REFERENCES RELQRELIQUIDA (RELQID)
);

-- 6. Cargue relleno
CREATE TABLE RELI_INFOAPSRELLENO (
  IARE_ID NUMBER PRIMARY KEY,
  RELI_ID NUMBER NOT NULL,
  QRS NUMBER,
  COSTO NUMBER,
  TARIFA NUMBER,
  USUA_USUA NUMBER,
  FECHA DATE DEFAULT SYSDATE,
  CONSTRAINT FK_IARE_RELQ FOREIGN KEY (RELI_ID) REFERENCES RELQRELIQUIDA (RELQID)
);

-- 7. Cargue adicional
CREATE TABLE RELI_INFOADICIONAL (
  CEAD_ID NUMBER PRIMARY KEY,
  RELI_ID NUMBER NOT NULL,
  CDF NUMBER,
  CTL NUMBER,
  USUA_USUA NUMBER,
  FECHA DATE DEFAULT SYSDATE,
  CONSTRAINT FK_CEAD_RELQ FOREIGN KEY (RELI_ID) REFERENCES RELQRELIQUIDA (RELQID)
);

-- 8. Auditoría usuarios
CREATE TABLE RELI_AUDIT_USUARIO (
  RAUS_ID NUMBER PRIMARY KEY,
  RELI_ID NUMBER NOT NULL,
  IUAE_ID NUMBER,
  USUA_USUA NUMBER,
  ACCION VARCHAR2(50) NOT NULL,
  FECHA DATE DEFAULT SYSDATE,
  CONSTRAINT FK_RAUS_RELQ FOREIGN KEY (RELI_ID) REFERENCES RELQRELIQUIDA (RELQID)
);

-- 9. Auditoría empresa
CREATE TABLE RELI_AUDIT_EMPRESA (
  RAEM_ID NUMBER PRIMARY KEY,
  RELI_ID NUMBER NOT NULL,
  INED_ID NUMBER,
  USUA_USUA NUMBER,
  ACCION VARCHAR2(50) NOT NULL,
  FECHA DATE DEFAULT SYSDATE,
  CONSTRAINT FK_RAEM_RELQ FOREIGN KEY (RELI_ID) REFERENCES RELQRELIQUIDA (RELQID)
);

-- 10. Auditoría APS
CREATE TABLE RELI_AUDIT_APS (
  RAAP_ID NUMBER PRIMARY KEY,
  RELI_ID NUMBER NOT NULL,
  IAED_ID NUMBER,
  USUA_USUA NUMBER,
  ACCION VARCHAR2(50) NOT NULL,
  FECHA DATE DEFAULT SYSDATE,
  CONSTRAINT FK_RAAP_RELQ FOREIGN KEY (RELI_ID) REFERENCES RELQRELIQUIDA (RELQID)
);

-- Vista comparativo de costos
CREATE OR REPLACE VIEW VREL_COMPARACOSTOS AS
SELECT R.RELQID AS COD_RELIQ,
       R.APSA_ID,
       R.RELQDESDE,
       R.RELQHASTA,
       NVL(A.COSTO, 0) AS COSTO_APS,
       NVL(E.COSTO, 0) AS COSTO_EMPRESA,
       (NVL(A.COSTO, 0) - NVL(E.COSTO, 0)) AS DIF_COSTO
  FROM RELQRELIQUIDA R
  LEFT JOIN RELI_INFOAPSEMPRDIVI A ON A.RELI_ID = R.RELQID
  LEFT JOIN RELI_INFOEMPRDIVI E ON E.RELI_ID = R.RELQID;

-- Vista comparativo tarifa de cobro
CREATE OR REPLACE VIEW VREL_COMPARATARIFACOBRO AS
SELECT R.RELQID AS RELI,
       R.APSA_ID,
       NVL(A.TARIFA, 0) AS TARIFA_APS,
       NVL(E.TARIFA, 0) AS TARIFA_EMPRESA,
       (NVL(A.TARIFA, 0) - NVL(E.TARIFA, 0)) AS DIF_TARIFA
  FROM RELQRELIQUIDA R
  LEFT JOIN RELI_INFOAPSEMPRDIVI A ON A.RELI_ID = R.RELQID
  LEFT JOIN RELI_INFOEMPRDIVI E ON E.RELI_ID = R.RELQID;

-- Package stubs
CREATE OR REPLACE PACKAGE PK_RELI AS
  FUNCTION freli_extraccion(
    p_apsaid NUMBER,
    p_relqid NUMBER,
    p_usuario NUMBER,
    p_desde VARCHAR2,
    p_hasta VARCHAR2
  ) RETURN VARCHAR2;
END PK_RELI;
/

CREATE OR REPLACE PACKAGE BODY PK_RELI AS
  FUNCTION freli_extraccion(
    p_apsaid NUMBER,
    p_relqid NUMBER,
    p_usuario NUMBER,
    p_desde VARCHAR2,
    p_hasta VARCHAR2
  ) RETURN VARCHAR2 IS
  BEGIN
    RETURN 'STUB_OK';
  END freli_extraccion;
END PK_RELI;
/

CREATE OR REPLACE PACKAGE PK_RELIQUIDAR AS
  FUNCTION freli_reliquidar(
    p_reliq NUMBER,
    p_aps NUMBER,
    p_out OUT CLOB
  ) RETURN VARCHAR2;
END PK_RELIQUIDAR;
/

CREATE OR REPLACE PACKAGE BODY PK_RELIQUIDAR AS
  FUNCTION freli_reliquidar(
    p_reliq NUMBER,
    p_aps NUMBER,
    p_out OUT CLOB
  ) RETURN VARCHAR2 IS
  BEGIN
    p_out := '{"status":"stub"}';
    RETURN 'STUB_OK';
  END freli_reliquidar;
END PK_RELIQUIDAR;
/

CREATE OR REPLACE PACKAGE PK_JSONRESUMEN AS
  FUNCTION freli_jsongral(
    p_reliq NUMBER,
    p_aps NUMBER,
    p_anno NUMBER,
    p_mes NUMBER
  ) RETURN CLOB;
END PK_JSONRESUMEN;
/

CREATE OR REPLACE PACKAGE BODY PK_JSONRESUMEN AS
  FUNCTION freli_jsongral(
    p_reliq NUMBER,
    p_aps NUMBER,
    p_anno NUMBER,
    p_mes NUMBER
  ) RETURN CLOB IS
  BEGIN
    RETURN '{"status":"stub"}';
  END freli_jsongral;
END PK_JSONRESUMEN;
/

CREATE OR REPLACE PACKAGE PKREI_UPDTARIFADOR AS
  FUNCTION fnrei_previsualizar(p_reliq NUMBER) RETURN CLOB;
  FUNCTION fnrei_previsualizar_iuae(p_reliq NUMBER) RETURN CLOB;
  FUNCTION fnrei_previsualizar_ined(p_reliq NUMBER) RETURN CLOB;
  FUNCTION fnrei_previsualizar_cead(p_reliq NUMBER) RETURN CLOB;
  FUNCTION fnrei_previsualizar_iare(p_reliq NUMBER) RETURN CLOB;
END PKREI_UPDTARIFADOR;
/

CREATE OR REPLACE PACKAGE BODY PKREI_UPDTARIFADOR AS
  FUNCTION fnrei_previsualizar(p_reliq NUMBER) RETURN CLOB IS
  BEGIN
    RETURN '{"status":"stub"}';
  END fnrei_previsualizar;

  FUNCTION fnrei_previsualizar_iuae(p_reliq NUMBER) RETURN CLOB IS
  BEGIN
    RETURN '{"status":"stub"}';
  END fnrei_previsualizar_iuae;

  FUNCTION fnrei_previsualizar_ined(p_reliq NUMBER) RETURN CLOB IS
  BEGIN
    RETURN '{"status":"stub"}';
  END fnrei_previsualizar_ined;

  FUNCTION fnrei_previsualizar_cead(p_reliq NUMBER) RETURN CLOB IS
  BEGIN
    RETURN '{"status":"stub"}';
  END fnrei_previsualizar_cead;

  FUNCTION fnrei_previsualizar_iare(p_reliq NUMBER) RETURN CLOB IS
  BEGIN
    RETURN '{"status":"stub"}';
  END fnrei_previsualizar_iare;
END PKREI_UPDTARIFADOR;
/

CREATE OR REPLACE PACKAGE PKREI_APLICARRELIQUIDA AS
  FUNCTION fnrei_aplicartodo(
    pint_reliid NUMBER,
    pint_usuusua NUMBER
  ) RETURN VARCHAR2;
END PKREI_APLICARRELIQUIDA;
/

CREATE OR REPLACE PACKAGE BODY PKREI_APLICARRELIQUIDA AS
  FUNCTION fnrei_aplicartodo(
    pint_reliid NUMBER,
    pint_usuusua NUMBER
  ) RETURN VARCHAR2 IS
  BEGIN
    RETURN 'STUB_OK';
  END fnrei_aplicartodo;
END PKREI_APLICARRELIQUIDA;
/

-- Índices mínimos (R-S0-T3)
CREATE INDEX IX_RELQRELIQUIDA_RELQID_APSAID ON RELQRELIQUIDA (RELQID, APSA_ID);
CREATE INDEX IX_FILTRO_COMPARACOSTO_RELI_ID ON FILTRO_COMPARACOSTO (RELQID);
CREATE INDEX IX_RELI_INFUSUAPSEMPRDIVI_RELI_ID ON RELI_INFUSUAPSEMPRDIVI (RELI_ID);
CREATE INDEX IX_RELI_INFOEMPRDIVI_RELI_ID ON RELI_INFOEMPRDIVI (RELI_ID);
CREATE INDEX IX_RELI_INFOAPSEMPRDIVI_RELI_ID ON RELI_INFOAPSEMPRDIVI (RELI_ID);
CREATE INDEX IX_RELI_INFOAPSRELLENO_RELI_ID ON RELI_INFOAPSRELLENO (RELI_ID);
CREATE INDEX IX_RELI_INFOADICIONAL_RELI_ID ON RELI_INFOADICIONAL (RELI_ID);
