-- ============================================
-- Módulo Rellenos Sanitarios
-- ============================================

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE AUCO_RELLENOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE SAUCO_RELLENOS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

CREATE TABLE AUCO_RELLENOS (
  RELL_ID            NUMBER(12)       NOT NULL,
  RELL_NOMRELLENO    VARCHAR2(180)    NOT NULL,
  RELL_DESCRIPCION   VARCHAR2(400),
  RELL_ESTADO        NUMBER(1)        DEFAULT 1 NOT NULL,
  RELL_PROPIO        NUMBER(1)        DEFAULT 0 NOT NULL,
  RELL_REGIONAL      NUMBER(1)        DEFAULT 0 NOT NULL,
  RELL_NUSD          VARCHAR2(30),
  RELL_FECHACREACION DATE             DEFAULT SYSDATE NOT NULL,
  USUA_USUA          NUMBER(12)       NOT NULL,
  CONSTRAINT PK_AUCO_RELLENOS PRIMARY KEY (RELL_ID),
  CONSTRAINT CK_AUCO_RELLENOS_ESTADO CHECK (RELL_ESTADO IN (0, 1)),
  CONSTRAINT CK_AUCO_RELLENOS_PROPIO CHECK (RELL_PROPIO IN (0, 1)),
  CONSTRAINT CK_AUCO_RELLENOS_REGION CHECK (RELL_REGIONAL IN (0, 1))
);
/

CREATE INDEX IX_AUCO_RELLENOS_NOMBRE ON AUCO_RELLENOS (RELL_NOMRELLENO);
CREATE INDEX IX_AUCO_RELLENOS_ESTADO ON AUCO_RELLENOS (RELL_ESTADO);
CREATE INDEX IX_AUCO_RELLENOS_NUSD ON AUCO_RELLENOS (RELL_NUSD);
/

CREATE SEQUENCE SAUCO_RELLENOS
  INCREMENT BY 1
  MINVALUE 1
  START WITH 1
  NOCYCLE
  CACHE 20
  NOORDER;
/

INSERT INTO AUCO_RELLENOS (
  RELL_ID, RELL_NOMRELLENO, RELL_DESCRIPCION, RELL_ESTADO, RELL_PROPIO, RELL_REGIONAL, RELL_NUSD, RELL_FECHACREACION, USUA_USUA
) VALUES (
  SAUCO_RELLENOS.NEXTVAL, 'Relleno Sanitario Norte', 'Relleno principal para zona norte', 1, 1, 0, 'NUSD-1001', SYSDATE, 1
);

INSERT INTO AUCO_RELLENOS (
  RELL_ID, RELL_NOMRELLENO, RELL_DESCRIPCION, RELL_ESTADO, RELL_PROPIO, RELL_REGIONAL, RELL_NUSD, RELL_FECHACREACION, USUA_USUA
) VALUES (
  SAUCO_RELLENOS.NEXTVAL, 'Relleno Regional Centro', 'Cobertura regional para municipios intermedios', 1, 0, 1, 'NUSD-2002', SYSDATE, 1
);

INSERT INTO AUCO_RELLENOS (
  RELL_ID, RELL_NOMRELLENO, RELL_DESCRIPCION, RELL_ESTADO, RELL_PROPIO, RELL_REGIONAL, RELL_NUSD, RELL_FECHACREACION, USUA_USUA
) VALUES (
  SAUCO_RELLENOS.NEXTVAL, 'Relleno Apoyo Occidente', 'Relleno de contingencia y respaldo operativo', 0, 0, 1, 'NUSD-3003', SYSDATE, 1
);

COMMIT;
/
