-- Fase 4 · Facturación
-- Crea/actualiza vistas base requeridas por la API.
-- Regla funcional: SIEMPRE consultar el período anterior (mes/anno ajustados en backend).
--
-- Nota: estas vistas se dejan con estructura mínima para habilitar integración
-- y evitar ORA-00942 mientras se completa el mapeo definitivo de fuentes.

CREATE OR REPLACE VIEW VEOLIA_APP.VACUO_FACTURACION AS
SELECT
    CAST(NULL AS NUMBER(10)) AS APS_ID,
    CAST(NULL AS NUMBER(4))  AS ANNO,
    CAST(NULL AS NUMBER(2))  AS MES
FROM dual
WHERE 1 = 0;

CREATE OR REPLACE VIEW VEOLIA_APP.VACUO_DETAFACTURACION AS
SELECT
    CAST(NULL AS NUMBER(10)) AS APS_ID,
    CAST(NULL AS NUMBER(4))  AS ANNO,
    CAST(NULL AS NUMBER(2))  AS MES
FROM dual
WHERE 1 = 0;

CREATE OR REPLACE VIEW VEOLIA_APP.VACUO_FACTURACIONCLUS AS
SELECT
    CAST(NULL AS NUMBER(10)) AS APS_ID,
    CAST(NULL AS NUMBER(4))  AS ANNO,
    CAST(NULL AS NUMBER(2))  AS MES
FROM dual
WHERE 1 = 0;

CREATE OR REPLACE VIEW VEOLIA_APP.VACUO_FACTURACIONDINC AS
SELECT
    CAST(NULL AS NUMBER(10)) AS APS_ID,
    CAST(NULL AS NUMBER(4))  AS ANNO,
    CAST(NULL AS NUMBER(2))  AS MES
FROM dual
WHERE 1 = 0;

CREATE OR REPLACE VIEW VEOLIA_APP.VAUCO_FATELECTRONICA AS
SELECT
    CAST(NULL AS NUMBER(10)) AS APS_ID,
    CAST(NULL AS NUMBER(4))  AS ANNO,
    CAST(NULL AS NUMBER(2))  AS MES
FROM dual
WHERE 1 = 0;
