-- Creación de tablas SUI_REVF* para módulo sui-reversiones
-- Schema: VEOLIA_APP
-- Adaptado de TARIFICADOR (AS-IS)

-- ============================================================
-- SUI_REVF19: Formulario 19 Reversado
-- ============================================================
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE SUI_REVF19 PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE SUI_REVF19 (
    REVE_ID     NUMBER(*,0) NOT NULL,
    APSA_ID     NUMBER(*,0) NOT NULL,
    F19_ANNO    NUMBER(*,0) NOT NULL,
    F19_MES     NUMBER(*,0) NOT NULL,
    F19_NJ      FLOAT(126) DEFAULT 0 NOT NULL,
    F19_NDJ     FLOAT(126) DEFAULT 0 NOT NULL,
    F19_CRTJ    FLOAT(126) DEFAULT 0 NOT NULL,
    F19_CDFJ    FLOAT(126) DEFAULT 0 NOT NULL,
    F19_QRTJ    FLOAT(126) DEFAULT 0 NOT NULL,
    F19_QRJ     FLOAT(126) DEFAULT 0 NOT NULL,
    F19_QBLJ    FLOAT(126) DEFAULT 0 NOT NULL,
    F19_QLUJ    FLOAT(126) DEFAULT 0 NOT NULL,
    F19_QNAZ    FLOAT(126) DEFAULT 0 NOT NULL,
    F19_QAJ     FLOAT(126) DEFAULT 0 NOT NULL,
    F19_FECHA   DATE DEFAULT SYSDATE NOT NULL,
    USUARIO     NUMBER(*,0) NOT NULL,
    CONSTRAINT PK_SUI_REVF19 PRIMARY KEY (REVE_ID, APSA_ID, F19_ANNO, F19_MES)
);

COMMENT ON TABLE SUI_REVF19 IS 'FORMULARIO 19 REVERSADO: VARIABLE PARA EL CALCULO DE LA TARIFA DE APROVECHAMIENTO Y TONELADAS CONJUNTAS - PRESTADORES DE RECOLECCIÓN Y TRANSPORTE DE RESIDUOS NO APROVECHABLES';

-- ============================================================
-- SUI_REVF23: Formulario 23 Reversado
-- ============================================================
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE SUI_REVF23 PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE SUI_REVF23 (
    REVE_ID         NUMBER(*,0) NOT NULL,
    APSA_ID         NUMBER(*,0) NOT NULL,
    EMPR_EMPR       NUMBER(*,0) NOT NULL,
    F23_ANNO        NUMBER(*,0) NOT NULL,
    F23_MES         NUMBER(*,0) NOT NULL,
    F23_ID          FLOAT(126) DEFAULT 0 NOT NULL,
    F23_NUAP        VARCHAR2(100) DEFAULT '0' NOT NULL,
    F23_N           FLOAT(126) DEFAULT 0 NOT NULL,
    F23_CP          FLOAT(126) DEFAULT 0 NOT NULL,
    F23_CCC         FLOAT(126) DEFAULT 0 NOT NULL,
    F23_M2CCJ       FLOAT(126) DEFAULT 0 NOT NULL,
    F23_CLAVJ       FLOAT(126) DEFAULT 0 NOT NULL,
    F23_M3AGUAJ     FLOAT(126) DEFAULT 0 NOT NULL,
    F23_M2LAVJ      FLOAT(126) DEFAULT 0 NOT NULL,
    F23_CLPJ        FLOAT(126) DEFAULT 0 NOT NULL,
    F23_KLPJ        FLOAT(126) DEFAULT 0 NOT NULL,
    F23_CCEI        FLOAT(126) DEFAULT 0 NOT NULL,
    F23_TIJ         FLOAT(126) DEFAULT 0 NOT NULL,
    F23_CCEMJ       FLOAT(126) DEFAULT 0 NOT NULL,
    F23_TMJ         FLOAT(126) DEFAULT 0 NOT NULL,
    F23_CLUS        FLOAT(126) DEFAULT 0 NOT NULL,
    F23_CBLJ        FLOAT(126) DEFAULT 0 NOT NULL,
    F23_LBLJ        FLOAT(126) DEFAULT 0 NOT NULL,
    F23_CBLS        FLOAT(126) DEFAULT 0 NOT NULL,
    F23_FACBLCLUS   FLOAT(126) DEFAULT 0 NOT NULL,
    F23_ABC         VARCHAR2(2) DEFAULT 'NO' NOT NULL,
    F23_FECHA       DATE DEFAULT SYSDATE NOT NULL,
    USUARIO         NUMBER(*,0) NOT NULL,
    CONSTRAINT PK_SUI_REVF23 PRIMARY KEY (REVE_ID, APSA_ID, EMPR_EMPR, F23_ANNO, F23_MES)
);

COMMENT ON TABLE SUI_REVF23 IS 'FORMULARIO 23 REVERSADO: COSTO DE LIMPIEZA URBANA Y COSTO DE BARRIDO Y LIMPIEZA DE VÍAS Y ÁREAS PÚBLICAS';
COMMENT ON COLUMN SUI_REVF23.F23_FACBLCLUS IS 'Factor de actualización del CBLS y del CLUS acumulado desde diciembre de 2014';

-- ============================================================
-- SUI_REVF24: Formulario 24 Reversado
-- ============================================================
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE SUI_REVF24 PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE SUI_REVF24 (
    REVE_ID         NUMBER(*,0) NOT NULL,
    APSA_ID         NUMBER(*,0) NOT NULL,
    F24_ANNO        NUMBER(*,0) NOT NULL,
    F24_MES         NUMBER(*,0) NOT NULL,
    F24_NUAP        VARCHAR2(100) DEFAULT '0' NOT NULL,
    F24_NUSD        VARCHAR2(100) DEFAULT '0' NOT NULL,
    F24_CENTROIDE   FLOAT(126) DEFAULT 0 NOT NULL,
    F24_QRT         FLOAT(126) DEFAULT 0 NOT NULL,
    F24_F1          FLOAT(126) DEFAULT 0 NOT NULL,
    F24_F2          FLOAT(126) DEFAULT 0 NOT NULL,
    F24_CPE         FLOAT(126) DEFAULT 0 NOT NULL,
    F24_PRTZ        FLOAT(126) DEFAULT 0 NOT NULL,
    F24_DET         FLOAT(126),
    F24_F1ET        FLOAT(126),
    F24_CPEET       FLOAT(126),
    F24_PRTZET      FLOAT(126),
    F24_CEG         FLOAT(126),
    F24_CRTP        FLOAT(126) DEFAULT 0 NOT NULL,
    F24_SALINIDAD   FLOAT(126) DEFAULT 0 NOT NULL,
    F24_VACRTABC    FLOAT(126) DEFAULT 0 NOT NULL,
    F24_VACRT       FLOAT(126) DEFAULT 0 NOT NULL,
    F24_FCK         FLOAT(126) DEFAULT 0 NOT NULL,
    F24_T           FLOAT(126) DEFAULT 0 NOT NULL,
    F24_CRTZ        FLOAT(126) DEFAULT 0 NOT NULL,
    F24_CRT         FLOAT(126) DEFAULT 0 NOT NULL,
    F24_FACRT       FLOAT(126) DEFAULT 0 NOT NULL,
    F24_FACCS       FLOAT(126) DEFAULT 0 NOT NULL,
    F24_FECHA       DATE DEFAULT SYSDATE NOT NULL,
    USUARIO         NUMBER(*,0) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_SUI_REVF24 PRIMARY KEY (REVE_ID, APSA_ID, F24_ANNO, F24_MES)
);

COMMENT ON TABLE SUI_REVF24 IS 'FORMATO 24 REVERSADO: COSTO DE RECOLECCION Y TRANSPORTE';
COMMENT ON COLUMN SUI_REVF24.F24_CENTROIDE IS 'Distancia desde el APS (centroide/limite) hasta el sitio de disposición final (km)';
COMMENT ON COLUMN SUI_REVF24.F24_FACRT IS 'Factor de actualización del CRT acumulado desde diciembre de 2014 Fac_acumulado';
COMMENT ON COLUMN SUI_REVF24.F24_FACCS IS 'Factor de actualización del CCS acumulado desde diciembre de 2014 FAc_acumulado';

-- ============================================================
-- SUI_REVF35: Formulario 35 Reversado
-- ============================================================
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE SUI_REVF35 PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE SUI_REVF35 (
    REVE_ID         NUMBER(*,0) NOT NULL,
    APSA_ID         NUMBER(*,0) NOT NULL,
    F35_ANNO        NUMBER(*,0) NOT NULL,
    F35_MES         NUMBER(*,0) NOT NULL,
    F35_NUSD        VARCHAR2(100) DEFAULT '0' NOT NULL,
    F35_NOMDF       VARCHAR2(100) DEFAULT '0' NOT NULL,
    F35_CAMRERS     FLOAT(126) DEFAULT 0 NOT NULL,
    F35_QRSMES      FLOAT(126) DEFAULT 0 NOT NULL,
    F35_QRSPROM     FLOAT(126) DEFAULT 0 NOT NULL,
    F35_CDFVU       FLOAT(126) DEFAULT 0 NOT NULL,
    F35_PERADDT     FLOAT(126) DEFAULT 0 NOT NULL,
    F35_CDFPC       FLOAT(126) DEFAULT 0 NOT NULL,
    F35_INCENTIVO   FLOAT(126) DEFAULT 0 NOT NULL,
    F35_DISPALT9    VARCHAR2(4) DEFAULT 'NO' NOT NULL,
    F35_INCCDFALT9  FLOAT(126) DEFAULT 0 NOT NULL,
    F35_VACDFABC    FLOAT(126) DEFAULT 0 NOT NULL,
    F35_VACDF       FLOAT(126) DEFAULT 0 NOT NULL,
    F35_PRCTCRRCP   FLOAT(126) DEFAULT 0 NOT NULL,
    F35_CDF         FLOAT(126) DEFAULT 0 NOT NULL,
    F35_CDFP        FLOAT(126) DEFAULT 0 NOT NULL,
    F35_FACCDF      FLOAT(126) DEFAULT 0 NOT NULL,
    F35_V0          FLOAT(126) DEFAULT 0 NOT NULL,
    F35_VM          FLOAT(126) DEFAULT 0 NOT NULL,
    F35_MCRS        FLOAT(126) DEFAULT 0 NOT NULL,
    F35_ICRSM       FLOAT(126) DEFAULT 0 NOT NULL,
    F35_ICCRS       FLOAT(126) DEFAULT 0 NOT NULL,
    F35_FREIN       FLOAT(126) DEFAULT 0 NOT NULL,
    F35_CAPREMDF    FLOAT(126) DEFAULT 0 NOT NULL,
    F35_FECHA       DATE DEFAULT SYSDATE NOT NULL,
    USUARIO         NUMBER(*,0) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_SUI_REVF35 PRIMARY KEY (REVE_ID, APSA_ID, F35_ANNO, F35_MES)
);

COMMENT ON TABLE SUI_REVF35 IS 'FORMULARIO 35 REVERSADO: COSTO DE DISPOSICIÓN FINAL OPERADOR SITIO DE DISPOSICION FINAL';
COMMENT ON COLUMN SUI_REVF35.F35_CAMRERS IS 'Capacidad mensual de recepción de residuos solidos';
COMMENT ON COLUMN SUI_REVF35.F35_DISPALT9 IS '¿Existe una disposición de la autoridad ambiental competente, que prohiba que la altura del relleno sanitario sea mayor a 9 metros';
COMMENT ON COLUMN SUI_REVF35.F35_INCCDFALT9 IS 'Incremento en el CDF por disposición menor a 2400 T/mes y altura restringida a 9 m (%)';
COMMENT ON COLUMN SUI_REVF35.F35_PRCTCRRCP IS 'Proporción del costo total que corresponde al costo de capital';
COMMENT ON COLUMN SUI_REVF35.F35_V0 IS 'Volumen total ocupado por residuos en las celdas activas, medido con topografia al final del semestre anterior al semestre de análisis (m3) - V0';
COMMENT ON COLUMN SUI_REVF35.F35_VM IS 'Volumen total ocupado por residuos en las celdas activas durante lo transcurrido del semestre de análisis, medido con topografia al final del mes de análisis (m3) - Vm';
COMMENT ON COLUMN SUI_REVF35.F35_MCRS IS 'Es la meta para el mes m del semestre de análisis, que corresponderá a la densidad de diseño del relleno sanitario.';
COMMENT ON COLUMN SUI_REVF35.F35_ICRSM IS 'Índice de compactación del relleno sanitario para el mes m dentro del semestre de análisis.';
COMMENT ON COLUMN SUI_REVF35.F35_ICCRS IS 'Índice de incumplimiento en la compactación del relleno sanitario';
COMMENT ON COLUMN SUI_REVF35.F35_FREIN IS 'Factor de reincidencia en el incumplimiento - Frein';
COMMENT ON COLUMN SUI_REVF35.F35_CAPREMDF IS 'Capacidad remanente del sitio de disp final (m3)';

-- ============================================================
-- SUI_REVF36: Formulario 36 Reversado
-- ============================================================
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE SUI_REVF36 PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE SUI_REVF36 (
    REVE_ID         NUMBER(*,0) NOT NULL,
    APSA_ID         NUMBER(*,0) NOT NULL,
    F36_ANNO        NUMBER(*,0) NOT NULL,
    F36_MES         NUMBER(*,0) NOT NULL,
    F36_NUSD        VARCHAR2(100) DEFAULT '0' NOT NULL,
    F36_NOMDPTO     VARCHAR2(100) DEFAULT '0' NOT NULL,
    F36_NOMMPIO     VARCHAR2(100) DEFAULT '0' NOT NULL,
    F36_NOMDF       VARCHAR2(100) DEFAULT '0' NOT NULL,
    F36_VLMES       FLOAT(126) DEFAULT 0 NOT NULL,
    F36_VLMPROM     FLOAT(126) DEFAULT 0 NOT NULL,
    F36_ESCENA      FLOAT(126) DEFAULT 0 NOT NULL,
    F36_CTLMVU      FLOAT(126) DEFAULT 0 NOT NULL,
    F36_ANNOPOSCLA  FLOAT(126) DEFAULT 0 NOT NULL,
    F36_CTLMPC      FLOAT(126) DEFAULT 0 NOT NULL,
    F36_CTLM        FLOAT(126) DEFAULT 0 NOT NULL,
    F36_CTLMX       FLOAT(126) DEFAULT 0 NOT NULL,
    F36_VACTLABC    FLOAT(126) DEFAULT 0 NOT NULL,
    F36_VACTL       FLOAT(126) DEFAULT 0 NOT NULL,
    F36_FCKCTL      FLOAT(126) DEFAULT 0 NOT NULL,
    F36_QRS         FLOAT(126) DEFAULT 0 NOT NULL,
    F36_CTL         FLOAT(126) DEFAULT 0 NOT NULL,
    F36_FACCTL      FLOAT(126) DEFAULT 0 NOT NULL,
    F36_FECHA       DATE DEFAULT SYSDATE NOT NULL,
    USUARIO         NUMBER(*,0) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_SUI_REVF36 PRIMARY KEY (REVE_ID, APSA_ID, F36_ANNO, F36_MES)
);

COMMENT ON TABLE SUI_REVF36 IS 'FORMULARIO 36 REVERSADO: COSTO DE TRATAMIENTO DE LIXIVIADOS - OPERADOR SITIO DE DISPOSICIÓN FINAL';
