CREATE TABLE TARIFICADOR.REVE_AUTORIZACION (
    APSA_ID NUMBER(10,0) NOT NULL,
    AUTO_ANNO NUMBER(4,0) NOT NULL,
    AUTO_MES NUMBER(2,0) NOT NULL,
    AUTO_DESCRIPCION VARCHAR2(4000 CHAR),
    AUTO_FECCREA DATE DEFAULT SYSDATE NOT NULL,
    USUA_USUARIO NUMBER(10,0) NOT NULL
);
