CREATE OR REPLACE VIEW TARIFICADOR.VREVE_AUTORIZACION AS
SELECT
    ra.APSA_ID,
    aps.APSA_NOMAPS,
    ra.AUTO_ANNO,
    ra.AUTO_MES,
    ra.AUTO_DESCRIPCION,
    ra.AUTO_FECCREA,
    su.SISU_CORREO,
    ra.USUA_USUARIO AS SISU_ID
FROM TARIFICADOR.REVE_AUTORIZACION ra
INNER JOIN TARIFICADOR.AUCO_APSASEO aps ON aps.APSA_ID = ra.APSA_ID
INNER JOIN TARIFICADOR.AUGE_SISUSUARIO su ON su.SISU_ID = ra.USUA_USUARIO;
