CREATE OR REPLACE VIEW VAUCO_TONELADAS AS
SELECT APS_ID AS APS,
       EMP_ID AS EMPRESA,
       MPIO_ID AS MPIO,
       IAED_ANNO AS ANNO,
       IAED_MES AS MES,
       'QBL' AS TIPO,
       NVL(IAED_QBL, 0) AS VALOR
  FROM AUCO_INFOAPSEMPRDIVI
UNION ALL
SELECT APS_ID AS APS,
       EMP_ID AS EMPRESA,
       MPIO_ID AS MPIO,
       IAED_ANNO AS ANNO,
       IAED_MES AS MES,
       'QLU' AS TIPO,
       NVL(IAED_QLU, 0) AS VALOR
  FROM AUCO_INFOAPSEMPRDIVI
UNION ALL
SELECT APS_ID AS APS,
       EMP_ID AS EMPRESA,
       MPIO_ID AS MPIO,
       IAED_ANNO AS ANNO,
       IAED_MES AS MES,
       'QNA' AS TIPO,
       NVL(IAED_QNA, 0) AS VALOR
  FROM AUCO_INFOAPSEMPRDIVI
UNION ALL
SELECT APS_ID AS APS,
       EMP_ID AS EMPRESA,
       MPIO_ID AS MPIO,
       IAED_ANNO AS ANNO,
       IAED_MES AS MES,
       'QA' AS TIPO,
       NVL(IAED_QA, 0) AS VALOR
  FROM AUCO_INFOAPSEMPRDIVI
UNION ALL
SELECT APS_ID AS APS,
       EMP_ID AS EMPRESA,
       MPIO_ID AS MPIO,
       IAED_ANNO AS ANNO,
       IAED_MES AS MES,
       'TAFNA' AS TIPO,
       NVL(IAED_TAFNA, 0) AS VALOR
  FROM AUCO_INFOAPSEMPRDIVI;
