-- ============================================================
-- DDL: Tablas requeridas por PK_VALGRAL
-- Schema: VEOLIA_APP
-- ============================================================

-- Tabla: AUCO_PODATECHO (Costo de Poda Techo)
CREATE TABLE AUCO_PODATECHO (
    APSA_ID         NUMBER NOT NULL,
    EMPR_EMPR       NUMBER NOT NULL,
    CPTE_ANNO       NUMBER NOT NULL,
    CPTE_MES        NUMBER NOT NULL,
    CPTE_VALORSUI   NUMBER,
    CPTE_VALORFACT  NUMBER
);

-- Tabla: AUCO_PROD2022 (Productividad)
CREATE TABLE AUCO_PROD2022 (
    APSA_ID         NUMBER NOT NULL,
    COSTO20010      NUMBER NOT NULL,
    PR22_ANNO       NUMBER NOT NULL,
    PR22_MES        NUMBER NOT NULL
);

-- Tabla: AUCO_APSRELLENO (Rellenos por APS)
CREATE TABLE AUCO_APSRELLENO (
    APSA_ID         NUMBER NOT NULL,
    APRE_PROPIO     NUMBER NOT NULL
);

-- Tabla: AUCO_TARICERTIFICADA (Tarifas Certificadas)
CREATE TABLE AUCO_TARICERTIFICADA (
    APSA_ID         NUMBER NOT NULL,
    TACE_ANNO       NUMBER NOT NULL,
    TACE_MES        NUMBER NOT NULL,
    TACE_FECINTEGRA DATE
);

-- Tabla: AUCO_COSTOSAPSRELLENO (Costos APS Relleno)
CREATE TABLE AUCO_COSTOSAPSRELLENO (
    APSA_ID         NUMBER NOT NULL,
    COST_ANNO       NUMBER NOT NULL,
    COST_MES        NUMBER NOT NULL
);

COMMIT;

-- Verificacion
SELECT 'AUCO_PODATECHO: ' || COUNT(*) FROM AUCO_PODATECHO;
SELECT 'AUCO_PROD2022: ' || COUNT(*) FROM AUCO_PROD2022;
SELECT 'AUCO_APSRELLENO: ' || COUNT(*) FROM AUCO_APSRELLENO;
SELECT 'AUCO_TARICERTIFICADA: ' || COUNT(*) FROM AUCO_TARICERTIFICADA;
SELECT 'AUCO_COSTOSAPSRELLENO: ' || COUNT(*) FROM AUCO_COSTOSAPSRELLENO;
