-- ============================================================
-- DDL: Suministros - Reversiones fase 3
-- Schema: VEOLIA_APP
-- ============================================================

CREATE TABLE VEOLIA_APP.AUCO_REVERSIONES (
    REVE_ID            NUMBER PRIMARY KEY,
    APSA_ID            NUMBER NOT NULL,
    REVE_ANNO          NUMBER NOT NULL,
    REVE_MES           NUMBER NOT NULL,
    REVE_MOTIVO        VARCHAR2(255) NOT NULL,
    APSA_FECHACREACION DATE DEFAULT SYSDATE NOT NULL,
    USUA_USUA          NUMBER NOT NULL,
    REVE_RESULTADO     NUMBER,
    REVE_MENSAJE       VARCHAR2(500)
);

CREATE SEQUENCE VEOLIA_APP.SAUCO_REVERSIONES
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE VEOLIA_APP.AUCO_REVEEMPRDIVI AS
SELECT * FROM VEOLIA_APP.AUCO_INFOEMPRDIVI WHERE 1 = 0;

CREATE TABLE VEOLIA_APP.AUCO_REVEAPSEMPRDIVI AS
SELECT * FROM VEOLIA_APP.AUCO_INFOAPSEMPRDIVI WHERE 1 = 0;

CREATE TABLE VEOLIA_APP.AUCO_REVEAPSRELLENO AS
SELECT * FROM VEOLIA_APP.AUCO_INFOAPSRELLENO WHERE 1 = 0;

CREATE TABLE VEOLIA_APP.AUCO_REVETARIFAS AS
SELECT * FROM VEOLIA_APP.AUCO_TARIFAS WHERE 1 = 0;

COMMIT;
