CREATE OR REPLACE PACKAGE VEOLIA_APP.PK_REVERSION AS
  FUNCTION fauco_reversion(
    aps IN INTEGER,
    mes IN INTEGER,
    anno IN INTEGER,
    motivo IN VARCHAR2,
    usuario IN INTEGER
  ) RETURN INTEGER;
END PK_REVERSION;
/

CREATE OR REPLACE PACKAGE BODY VEOLIA_APP.PK_REVERSION AS
  FUNCTION fauco_reversion(
    aps IN INTEGER,
    mes IN INTEGER,
    anno IN INTEGER,
    motivo IN VARCHAR2,
    usuario IN INTEGER
  ) RETURN INTEGER IS
    v_reve_id NUMBER;
  BEGIN
    SELECT VEOLIA_APP.SAUCO_REVERSIONES.NEXTVAL INTO v_reve_id FROM dual;

    INSERT INTO VEOLIA_APP.AUCO_REVEEMPRDIVI
    SELECT *
      FROM VEOLIA_APP.AUCO_INFOEMPRDIVI
     WHERE INED_ANNO = anno
       AND INED_MES = mes;

    INSERT INTO VEOLIA_APP.AUCO_REVEAPSEMPRDIVI
    SELECT *
      FROM VEOLIA_APP.AUCO_INFOAPSEMPRDIVI
     WHERE IAED_ANNO = anno
       AND IAED_MES = mes;

    INSERT INTO VEOLIA_APP.AUCO_REVEAPSRELLENO
    SELECT *
      FROM VEOLIA_APP.AUCO_INFOAPSRELLENO
     WHERE IARE_ANNO = anno
       AND IARE_MES = mes;

    INSERT INTO VEOLIA_APP.AUCO_REVETARIFAS
    SELECT *
      FROM VEOLIA_APP.AUCO_TARIFAS
     WHERE TARI_ANNO = anno
       AND TARI_MES = mes;

    DELETE FROM VEOLIA_APP.AUCO_INFOEMPRDIVI
     WHERE INED_ANNO = anno
       AND INED_MES = mes;

    DELETE FROM VEOLIA_APP.AUCO_INFOAPSEMPRDIVI
     WHERE IAED_ANNO = anno
       AND IAED_MES = mes;

    DELETE FROM VEOLIA_APP.AUCO_INFOAPSRELLENO
     WHERE IARE_ANNO = anno
       AND IARE_MES = mes;

    DELETE FROM VEOLIA_APP.AUCO_TARIFAS
     WHERE TARI_ANNO = anno
       AND TARI_MES = mes;

    INSERT INTO VEOLIA_APP.AUCO_REVERSIONES (
      REVE_ID,
      APSA_ID,
      REVE_ANNO,
      REVE_MES,
      REVE_MOTIVO,
      USUA_USUA,
      REVE_RESULTADO,
      REVE_MENSAJE
    ) VALUES (
      v_reve_id,
      aps,
      CASE WHEN mes = 12 THEN anno + 1 ELSE anno END,
      CASE WHEN mes = 12 THEN 1 ELSE mes + 1 END,
      motivo,
      usuario,
      1,
      'OK'
    );

    COMMIT;
    RETURN 1;
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      RETURN 0;
  END;
END PK_REVERSION;
/

SHOW ERRORS PACKAGE VEOLIA_APP.PK_REVERSION;
SHOW ERRORS PACKAGE BODY VEOLIA_APP.PK_REVERSION;
