-- Creación de tablas y objetos para Fase 1: Cargue y Certificación
-- Schema: VEOLIA_APP

-- ============================================================
-- Tablas faltantes de Cargue
-- ============================================================

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE AUCO_CARGUECOMERCIAL PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE AUCO_CARGUECOMERCIAL (
    CCOM_ID         NUMBER NOT NULL,
    RCOM_ID         NUMBER NOT NULL,
    CCOM_CODAPS     NUMBER NOT NULL,
    CCOM_APSNOM     VARCHAR2(150) NOT NULL,
    CCOM_ANNO       NUMBER NOT NULL,
    CCOM_MES        NUMBER NOT NULL,
    CCOM_CU         NUMBER NOT NULL,
    CCOM_NOMCU      VARCHAR2(100) NOT NULL,
    CCOM_CODFACTOR  NUMBER NOT NULL,
    CCOM_CODTIPO    NUMBER NOT NULL,
    CCOM_TIPO       NUMBER NOT NULL,
    CCOM_NOMTIPO    VARCHAR2(150) NOT NULL,
    CCOM_CANTIDAD   NUMBER NOT NULL,
    CCOM_TONELADAS  NUMBER NOT NULL,
    CCOM_FECRE      DATE DEFAULT SYSDATE NOT NULL,
    CCOM_USUCRE     NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT AUCO_CARGUECOMERCIAL_PK PRIMARY KEY (CCOM_ID)
);

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE AUCO_RESCOMERCIAL PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE AUCO_RESCOMERCIAL (
    RCOM_ID     NUMBER NOT NULL,
    APSA_ID     NUMBER NOT NULL,
    RCOM_ANNO   NUMBER NOT NULL,
    RCOM_MES    NUMBER NOT NULL,
    RCOM_N      NUMBER NOT NULL,
    RCOM_ND     NUMBER NOT NULL,
    RCOM_NA     NUMBER NOT NULL,
    RCOM_TAFNA  NUMBER NOT NULL,
    RCOM_FECRE  DATE DEFAULT SYSDATE NOT NULL,
    RCOM_USUCRE NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT AUCO_RESCOMERCIAL_PK PRIMARY KEY (RCOM_ID)
);

ALTER TABLE AUCO_CARGUECOMERCIAL ADD CONSTRAINT FK_AUCO_RESCOMERCIAL FOREIGN KEY (RCOM_ID) REFERENCES AUCO_RESCOMERCIAL(RCOM_ID);

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE AUCO_CARGUEUSUSEM PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE AUCO_CARGUEUSUSEM (
    CAUS_CODAPS     NUMBER NOT NULL,
    CAUS_APSNOM     VARCHAR2(150) NOT NULL,
    CAUS_ANNO       NUMBER NOT NULL,
    CAUS_SEMESTRE   NUMBER NOT NULL,
    CAUS_CODCU      NUMBER NOT NULL,
    CAUS_NOMCU      VARCHAR2(100) NOT NULL,
    CAUS_CODFACTOR  NUMBER NOT NULL,
    CAUS_NOMFACTOR  NUMBER NOT NULL,
    CAUS_CODTIPO    NUMBER NOT NULL,
    CAUS_NOMTIPO    VARCHAR2(150) NOT NULL,
    CAUS_CANTM1     NUMBER NOT NULL,
    CAUS_CANTM2     NUMBER NOT NULL,
    CAUS_CANTM3     NUMBER NOT NULL,
    CAUS_CANTM4     NUMBER NOT NULL,
    CAUS_CANTM5     NUMBER NOT NULL,
    CAUS_CANTM6     NUMBER NOT NULL,
    CAUS_TONM1      NUMBER NOT NULL,
    CAUS_TONM2      NUMBER NOT NULL,
    CAUS_TONM3      NUMBER NOT NULL,
    CAUS_TONM4      NUMBER NOT NULL,
    CAUS_TONM5      NUMBER NOT NULL,
    CAUS_TONM6      NUMBER NOT NULL,
    CAUS_FECRE      DATE DEFAULT SYSDATE NOT NULL,
    CAUS_USUCRE     NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT AUCO_CARGUEUSUSEM_PK PRIMARY KEY (CAUS_CODAPS, CAUS_ANNO, CAUS_SEMESTRE, CAUS_CODCU, CAUS_CODFACTOR, CAUS_CODTIPO)
);

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE AUCO_CARGUEPROPIO PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE AUCO_CARGUEPROPIO (
    APSA_ID         NUMBER(*,0) NOT NULL,
    EMPR_EMPR       NUMBER(*,0) NOT NULL,
    PROP_ANNO       NUMBER(*,0) NOT NULL,
    PROP_MES        NUMBER(*,0) NOT NULL,
    PROP_QRT        FLOAT(126) DEFAULT 0 NOT NULL,
    PROP_QLU        FLOAT(126) DEFAULT 0 NOT NULL,
    PROP_QNA        FLOAT(126) DEFAULT 0 NOT NULL,
    PROP_QBL        FLOAT(126) DEFAULT 0 NOT NULL,
    PROP_QR         FLOAT(126) DEFAULT 0 NOT NULL,
    PROP_QRS        FLOAT(126) DEFAULT 0 NOT NULL,
    PROP_CBLJ       FLOAT(126) DEFAULT 0 NOT NULL,
    PROP_LBL        FLOAT(126) DEFAULT 0 NOT NULL,
    PROP_MT3AGUA    FLOAT(126) DEFAULT 0 NOT NULL,
    PROP_CP         FLOAT(126) DEFAULT 0 NOT NULL,
    PROP_M2CC       FLOAT(126) DEFAULT 0 NOT NULL,
    PROP_M2LAV      FLOAT(126) DEFAULT 0 NOT NULL,
    PROP_TI         FLOAT(126) DEFAULT 0 NOT NULL,
    PROP_TM         FLOAT(126) DEFAULT 0 NOT NULL,
    PROP_KLP        FLOAT(126) DEFAULT 0 NOT NULL,
    PROP_VL         FLOAT(126) DEFAULT 0 NOT NULL,
    PROP_ESCENARIO  FLOAT(126) DEFAULT 0 NOT NULL,
    PROP_CTLMX      FLOAT(126) DEFAULT 0 NOT NULL,
    PROP_T          FLOAT(126) DEFAULT 0 NOT NULL,
    PROP_CPE        FLOAT(126) DEFAULT 0 NOT NULL,
    PROP_VACRT      FLOAT(126) DEFAULT 0 NOT NULL,
    PROP_VACRTABC   FLOAT(126) DEFAULT 0 NOT NULL,
    PROP_VACDF      FLOAT(126) DEFAULT 0 NOT NULL,
    PROP_VACDFABC   FLOAT(126) DEFAULT 0 NOT NULL,
    PROP_NAA        FLOAT(126) DEFAULT 0 NOT NULL,
    PROP_QA         FLOAT(126) DEFAULT 0 NOT NULL,
    PROP_TAFA       FLOAT(126) DEFAULT 0 NOT NULL,
    PROP_CRTPROPIO  FLOAT(126) DEFAULT 0 NOT NULL,
    PROP_QRTPROPIO  FLOAT(126) DEFAULT 0 NOT NULL,
    PROP_CDFPROPIO  FLOAT(126) DEFAULT 0 NOT NULL,
    PROP_FECCREA    DATE DEFAULT SYSDATE,
    USUA_USUARIO    NUMBER(*,0) NOT NULL,
    CONSTRAINT PK_AUCO_CARGUEPROPIO PRIMARY KEY (APSA_ID, EMPR_EMPR, PROP_ANNO, PROP_MES)
);

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE AUCO_CARGUEPROPIOSEM PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE AUCO_CARGUEPROPIOSEM (
    APSA_ID         NUMBER(*,0) NOT NULL,
    EMPR_EMPR       NUMBER(*,0) NOT NULL,
    PROP_ANNO       NUMBER(*,0) NOT NULL,
    PROP_MES        NUMBER(*,0) NOT NULL,
    PROP_QRT        FLOAT(126) DEFAULT 0 NOT NULL,
    PROP_QLU        FLOAT(126) DEFAULT 0 NOT NULL,
    PROP_QNA        FLOAT(126) DEFAULT 0 NOT NULL,
    PROP_QBL        FLOAT(126) DEFAULT 0 NOT NULL,
    PROP_QR         FLOAT(126) DEFAULT 0 NOT NULL,
    PROP_QRS        FLOAT(126) DEFAULT 0 NOT NULL,
    PROP_LBL        FLOAT(126) DEFAULT 0 NOT NULL,
    PROP_VL         FLOAT(126) DEFAULT 0 NOT NULL,
    PROP_ESCENARIO  FLOAT(126) DEFAULT 0 NOT NULL,
    PROP_CTLMX      FLOAT(126) DEFAULT 0 NOT NULL,
    PROP_CPE        FLOAT(126) DEFAULT 0 NOT NULL,
    PROP_NAA        FLOAT(126) DEFAULT 0 NOT NULL,
    PROP_TAFA       FLOAT(126) DEFAULT 0 NOT NULL,
    PROP_CRTPROPIO  FLOAT(126) DEFAULT 0 NOT NULL,
    PROP_CDFPROPIO  FLOAT(126) DEFAULT 0 NOT NULL,
    PROP_FECCREA    DATE DEFAULT SYSDATE,
    USUA_USUARIO    NUMBER(*,0) NOT NULL,
    PROP_QRSMUNRECP FLOAT(126) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_AUCO_CARGUEPROPIOSEM PRIMARY KEY (APSA_ID, EMPR_EMPR, PROP_ANNO, PROP_MES)
);

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE AUCO_CARGUECOMPE PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE AUCO_CARGUECOMPE (
    APSA_ID     NUMBER(*,0) NOT NULL,
    EMPR_EMPR   NUMBER(*,0) NOT NULL,
    COMP_ANNO   NUMBER(*,0) NOT NULL,
    COMP_MES    NUMBER(*,0) NOT NULL,
    COMP_N      FLOAT(126) DEFAULT 0 NOT NULL,
    COMP_NAA    FLOAT(126) DEFAULT 0 NOT NULL,
    COMP_NDA    FLOAT(126) DEFAULT 0 NOT NULL,
    COMP_TAFNA  FLOAT(126) DEFAULT 0 NOT NULL,
    COMP_MT3AGUA FLOAT(126) DEFAULT 0 NOT NULL,
    COMP_QRT    FLOAT(126) DEFAULT 0 NOT NULL,
    COMP_QLU    FLOAT(126) DEFAULT 0 NOT NULL,
    COMP_QNA    FLOAT(126) DEFAULT 0 NOT NULL,
    COMP_QBL    FLOAT(126) DEFAULT 0 NOT NULL,
    COMP_QR     FLOAT(126) DEFAULT 0 NOT NULL,
    COMP_QRS    FLOAT(126) DEFAULT 0 NOT NULL,
    COMP_CBLJ   FLOAT(126) DEFAULT 0 NOT NULL,
    COMP_LBLCOM FLOAT(126) DEFAULT 0 NOT NULL,
    COMP_CP     FLOAT(126) DEFAULT 0 NOT NULL,
    COMP_M2CC   FLOAT(126) DEFAULT 0 NOT NULL,
    COMP_M2LAV  FLOAT(126) DEFAULT 0 NOT NULL,
    COMP_TI     FLOAT(126) DEFAULT 0 NOT NULL,
    COMP_TM     FLOAT(126) DEFAULT 0 NOT NULL,
    COMP_KLP    FLOAT(126) DEFAULT 0 NOT NULL,
    COMP_QA     FLOAT(126) DEFAULT 0 NOT NULL,
    COMP_TAFA   FLOAT(126) DEFAULT 0 NOT NULL,
    COMP_CRTVBA FLOAT(126) DEFAULT 0 NOT NULL,
    COMP_CDFVBA FLOAT(126) DEFAULT 0 NOT NULL,
    COMP_CTLRELL FLOAT(126) DEFAULT 0 NOT NULL,
    COMP_INCEN  FLOAT(126) DEFAULT 0 NOT NULL,
    COMP_CDFRELL FLOAT(126) DEFAULT 0 NOT NULL,
    COMP_FECCREA DATE DEFAULT SYSDATE,
    USUA_USUARIO NUMBER(*,0) NOT NULL,
    CONSTRAINT PK_AUCO_CARGUECOMPE PRIMARY KEY (APSA_ID, EMPR_EMPR, COMP_ANNO, COMP_MES)
);

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE AUCO_CARGUECOMPESEM PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE AUCO_CARGUECOMPESEM (
    APSA_ID     NUMBER(*,0) NOT NULL,
    EMPR_EMPR   NUMBER(*,0) NOT NULL,
    COMP_ANNO   NUMBER(*,0) NOT NULL,
    COMP_MES    NUMBER(*,0) NOT NULL,
    COMP_N      FLOAT(126) DEFAULT 0 NOT NULL,
    COMP_NAA    FLOAT(126) DEFAULT 0 NOT NULL,
    COMP_NDA    FLOAT(126) DEFAULT 0 NOT NULL,
    COMP_QLU    FLOAT(126) DEFAULT 0 NOT NULL,
    COMP_QNA    FLOAT(126) DEFAULT 0 NOT NULL,
    COMP_QBL    FLOAT(126) DEFAULT 0 NOT NULL,
    COMP_QR     FLOAT(126) DEFAULT 0 NOT NULL,
    COMP_CBLJ   FLOAT(126) DEFAULT 0 NOT NULL,
    COMP_LBLCOM FLOAT(126) DEFAULT 0 NOT NULL,
    COMP_CRTVBA FLOAT(126) DEFAULT 0 NOT NULL,
    COMP_CDFVBA FLOAT(126) DEFAULT 0 NOT NULL,
    COMP_QRT    FLOAT(126) DEFAULT 0 NOT NULL,
    COMP_FECCREA DATE DEFAULT SYSDATE,
    USUA_USUARIO NUMBER(*,0) NOT NULL,
    CONSTRAINT PK_AUCO_CARGUECOMPESEM PRIMARY KEY (APSA_ID, EMPR_EMPR, COMP_ANNO, COMP_MES)
);

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE AUCO_CARGUETERCERO PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE AUCO_CARGUETERCERO (
    APSA_ID         NUMBER(*,0) NOT NULL,
    TERC_ANNO       NUMBER(*,0) NOT NULL,
    TERC_MES        NUMBER(*,0) NOT NULL,
    TERC_CDF        FLOAT(126) DEFAULT 0 NOT NULL,
    TERC_CTL        FLOAT(126) DEFAULT 0 NOT NULL,
    TERC_INCENTIVOCDF FLOAT(126) DEFAULT 0 NOT NULL,
    TERC_FECCREA    DATE DEFAULT SYSDATE,
    USUA_USUARIO    NUMBER(*,0) NOT NULL,
    CONSTRAINT PK_AUCO_CARGUETERCERO PRIMARY KEY (APSA_ID, TERC_ANNO, TERC_MES)
);

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE AUCO_CARGUERURAL PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE AUCO_CARGUERURAL (
    APSA_ID         NUMBER(*,0) NOT NULL,
    RURA_ANNO       NUMBER(*,0) NOT NULL,
    RURA_SEMESTRE   NUMBER(*,0) NOT NULL,
    RURA_QRT        FLOAT(126) DEFAULT 0 NOT NULL,
    COMP_FECCREA    DATE DEFAULT SYSDATE,
    USUA_USUARIO    NUMBER(*,0) NOT NULL,
    CONSTRAINT PK_AUCO_CARGUERURAL PRIMARY KEY (APSA_ID, RURA_ANNO, RURA_SEMESTRE)
);

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE AUCO_CERTADICIONAL PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE AUCO_CERTADICIONAL (
    CEAD_ID         NUMBER NOT NULL,
    EMPR_EMPR       NUMBER NOT NULL,
    DIVI_DIVI       NUMBER NOT NULL,
    APSA_ID         NUMBER NOT NULL,
    RELL_ID         NUMBER NOT NULL,
    CEAD_ANNO       NUMBER NOT NULL,
    CEAD_MES        NUMBER NOT NULL,
    CEAD_ANNOSEMEST NUMBER DEFAULT 0 NOT NULL,
    CEAD_CDF        FLOAT(126) DEFAULT 0,
    CEAD_CTL        FLOAT(126) DEFAULT 0,
    CEAD_FECHACREACION DATE DEFAULT SYSDATE,
    USUA_USUA       NUMBER NOT NULL,
    CEAD_TON        FLOAT(126) DEFAULT 0,
    CEAD_VARIACION  FLOAT(126) DEFAULT 0,
    CEAD_CRT        FLOAT(126) DEFAULT 0,
    CEAD_QRS        FLOAT(126) DEFAULT 0,
    CEAD_QRT        FLOAT(126) DEFAULT 0,
    CEAD_DINC       FLOAT(126) DEFAULT 0,
    CEAD_INCENTIVO  FLOAT(126) DEFAULT 0,
    CONSTRAINT PK_TAR_CERTADICIONAL PRIMARY KEY (CEAD_ID)
);

CREATE UNIQUE INDEX IXAUCO_CERTADICIONAL01 ON AUCO_CERTADICIONAL (EMPR_EMPR, DIVI_DIVI, APSA_ID, RELL_ID, CEAD_ANNO, CEAD_MES);

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PORD_PROPIA PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PORD_PROPIA (
    CODAPS      NUMBER(6,0) DEFAULT 0,
    NOMAPS      VARCHAR2(100),
    CODEMPRESA  NUMBER(6,0) DEFAULT 0,
    NOMEMPRESA  VARCHAR2(200),
    PRODANNO    NUMBER(4,0) DEFAULT 0,
    PRODMES     NUMBER(2,0) DEFAULT 0,
    PRODCCS     NUMBER(10,5) DEFAULT 0,
    PRODCBLS    NUMBER(10,5) DEFAULT 0,
    PRODCLUS    NUMBER(10,5) DEFAULT 0,
    PRODCRT     NUMBER(10,5) DEFAULT 0,
    PRODCDF     NUMBER(10,5) DEFAULT 0,
    PRODCTL     NUMBER(10,5) DEFAULT 0,
    CONSTRAINT PK_PORD_PROPIA PRIMARY KEY (CODAPS, CODEMPRESA, PRODANNO, PRODMES)
);

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PORD_TERCERO PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PORD_TERCERO (
    CODAPS      NUMBER(6,0) DEFAULT 0,
    NOMAPS      VARCHAR2(100),
    CODEMPRESA  NUMBER(6,0) DEFAULT 0,
    NOMEMPRESA  VARCHAR2(200),
    TERCANNO    NUMBER(4,0) DEFAULT 0,
    TERCMES     NUMBER(2,0) DEFAULT 0,
    TERCCCS     NUMBER(10,5) DEFAULT 0,
    TERCCBLS    NUMBER(10,5) DEFAULT 0,
    TERCCLUS    NUMBER(10,5) DEFAULT 0,
    TERCCRT     NUMBER(10,5) DEFAULT 0,
    TERCCDF     NUMBER(10,5) DEFAULT 0,
    TERCCTL     NUMBER(10,5) DEFAULT 0,
    CONSTRAINT PK_PORD_TERCERO PRIMARY KEY (CODAPS, CODEMPRESA, TERCANNO, TERCMES)
);

-- Tablas adicionales referenciadas en packages
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE USUASEMESTRE PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE USUASEMESTRE (
    CODAPS      NUMBER,
    FACTOR      NUMBER,
    USO         NUMBER,
    CODTAR      NUMBER,
    USUANNO     NUMBER,
    USUMES      NUMBER,
    CANT        NUMBER,
    TON         NUMBER,
    N           NUMBER DEFAULT 0,
    NA          NUMBER DEFAULT 0,
    ND          NUMBER DEFAULT 0,
    TAFNA       NUMBER DEFAULT 0
);

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PGIRS_VALVARIABLE PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PGIRS_VALVARIABLE (
    PGRIANNO    NUMBER,
    PGRIMES     NUMBER,
    APSAID      NUMBER,
    PGRIVARIABLE NUMBER,
    PGRIVALOR   NUMBER,
    NOMVARIABLE VARCHAR2(15)
);

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PGIRS_INFORME PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PGIRS_INFORME (
    APSID           NUMBER,
    PERIODO         VARCHAR2(6),
    BARRIDO         NUMBER DEFAULT 0,
    BARRIDOPGIRS    NUMBER DEFAULT 0,
    BARRIDOCOLOR    VARCHAR2(10),
    PODA            NUMBER DEFAULT 0,
    PODAPGIRS       NUMBER DEFAULT 0,
    PODACOLOR       VARCHAR2(10),
    CESPED          NUMBER DEFAULT 0,
    CESPEDPGIRS     NUMBER DEFAULT 0,
    CESPEDCOLOR     VARCHAR2(10),
    LAVADO          NUMBER DEFAULT 0,
    LAVADOPGIRS     NUMBER DEFAULT 0,
    LAVADOCOLOR     VARCHAR2(10),
    PLAYAS          NUMBER DEFAULT 0,
    PLAYASPGIRS     NUMBER DEFAULT 0,
    PLAYASCOLOR     VARCHAR2(10),
    CESTASINS       NUMBER DEFAULT 0,
    CESTASINSPGIRS  NUMBER DEFAULT 0,
    CESTASINSCOLOR  VARCHAR2(10),
    CESTASMAN       NUMBER DEFAULT 0,
    CESTASMANPGIRS  NUMBER DEFAULT 0,
    CESTASMANCOLOR  VARCHAR2(10)
);

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE AUCO_MESESCRA PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE AUCO_MESESCRA (
    MECR_ID         NUMBER,
    MECR_SEMESREAL  NUMBER
);

-- ============================================================
-- Secuencias
-- ============================================================

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE SAUCO_INFOEMPRDIVI';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE SEQUENCE SAUCO_INFOEMPRDIVI INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER;

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE SAUCO_INFOAPSEMPRDIVI';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE SEQUENCE SAUCO_INFOAPSEMPRDIVI INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER;

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE SAUCO_INFOAPSRELLENO';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE SEQUENCE SAUCO_INFOAPSRELLENO INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER;

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE SAUCO_INFUSUAPSEMPRDIVI';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE SEQUENCE SAUCO_INFUSUAPSEMPRDIVI INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER;

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE SAUCO_CERTADICIONAL';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE SEQUENCE SAUCO_CERTADICIONAL INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER;

COMMIT;
