CREATE OR REPLACE VIEW VAUCO_LBL AS
SELECT IAD.APS_ID AS APS,
       IAD.EMP_ID AS EMPRESA,
       IAD.MPIO_ID AS MPIO,
       IAD.IAED_ANNO AS ANNO,
       IAD.IAED_MES AS MES,
       NVL(IAD.INED_LBL, 0) AS VALOR,
       APD.APEM_ESTADO AS ESTADO
  FROM AUCO_INFOEMPRDIVI IAD
  JOIN AUCO_APSEMPRDIVI APD
    ON APD.APS_ID = IAD.APS_ID
   AND APD.EMP_ID = IAD.EMP_ID
 WHERE APD.APEM_ESTADO = 1;
